###REST ECHO
GET http://localhost:8125/echo?msg=nodejs&title=hello

###REST ADD
GET http://localhost:8125/sum?a=3&b=4

###REST SUBSTRACT
GET http://localhost:8125/sub?a=4&b=3

###REST AVG
GET http://localhost:8125/avg?a=1&b=2&c=3&d=4&e=5