###test home
GET http://localhost:8125/home?apikey=qwer
###test home/welcome
GET http://localhost:8125/home/welcome?apikey=qwer
###test about
GET http://localhost:8125/about?apikey=qwer
###test blog
GET http://localhost:8125/blog?apikey=qwer